"""Execution owns its atomic state boundary."""
from typing import Callable, Protocol


class OperationStore(Protocol):
    def read(self, grant_id: str) -> dict: ...
    def transact(self, grant_id: str, change: Callable[[dict | None], dict]) -> dict:
        """Commit the returned state atomically, or leave storage unchanged."""
        ...


class FileReader(Protocol):
    def read_files(self, files: list[dict], max_bytes: int) -> list[dict]: ...
    def inspect_file(self, path: str, max_bytes: int) -> dict: ...


class FileWriter(Protocol):
    def apply_change(self, path: str, before_hash: str | None, content: str | None, max_bytes: int) -> dict: ...


class CheckRunner(Protocol):
    def contract_hash(self, check_id: str) -> str: ...
    def run_operation(self, operation_id: str, payload_hash: str, check_id: str, *, expected_contract: str, max_bytes: int,
                  timeout: float, stopped: Callable[[], bool]) -> dict: ...
    def completion(self, operation_id: str, payload_hash: str, expected_contract: str) -> dict: ...
    def retire_operation(self, operation_id: str, payload_hash: str, expected_contract: str) -> dict: ...
