from typing import Protocol, ContextManager

from .domain.model import Capabilities, Receipt


class Conflict(RuntimeError):
    pass


class DeliveryStore(Protocol):
    def read(self) -> dict: ...
    def save(self, ledger: dict, expected_revision: int) -> None: ...


class AcceptedResults(Protocol):
    def accepted_result(self, run_id: str, node_id: str) -> dict: ...


class Destination(Protocol):
    def capabilities(self) -> Capabilities: ...
    def validate(self, payload: dict) -> None:
        """Check exact owned environment and operation before effects; no writes."""
        ...
    def send(self, payload: dict, operation_key: str) -> Receipt: ...
    def find(self, operation_key: str, payload_hash: str) -> Receipt | None:
        """None means no proof. It is never sufficient authority to resend."""
        ...


class LifecycleStore(Protocol):
    def locked(self) -> ContextManager: ...
    def read(self) -> dict | None: ...
    def save(self, state: dict) -> None: ...


class EnvironmentRepository(Protocol):
    def new_identity(self, task: str, environment_id: str) -> dict: ...
    def validate(self, state: dict): ...
    def execute(self, state: dict, operation: str, operation_id: str) -> str: ...
    def receipt(self, state: dict) -> dict | None: ...
    def creation_ready(self, state: dict): ...
    def creation_rejection(self, state: dict) -> dict | None: ...
    def describe(self, state: dict) -> dict: ...
    def endpoint(self, state: dict) -> str: ...
    def no_change_retirement(self, state: dict) -> None: ...
    def retirement_proof(self, state: dict) -> dict | None: ...
